### ISSUE TITLE
Followed instructions, missing file.

### ISSUE THREAD

**Issue by arthurwolf** [ProjectNUWA/DragNUWA#27]
I followed the instructions in the Readme.

When trying to run the download.sh file, I get:

```
Failed to retrieve file url:

        Too many users have viewed or downloaded this file recently. Please
        try accessing the file again later. If the file you are trying to
        access is particularly large or is shared with many people, it may
        take up to 24 hours to be able to view or download the file. If you
        still can't access a file after 24 hours, contact your domain
        administrator.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1Z4JOley0SJCb35kFF4PCc6N6P1ftfX4i

but Gdown can't. Please check connections and permissions.
```

So I just download it directly in the browser and copy the file to models/.

```
╰─(DragNUWA) ⠠⠵ ls models                                                                                                  on main|…1
4799.pth  Download.sh
```

Then when I try to run the demo script, the following happens:

```
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #3: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #4: ConcatTimestepEmbedderND with 0 params. Trainable: False
parameters of gaussian kernel: kernel_size: 199, sigma: 20, channels: 2
Lora successfully injected into Net.
Traceback (most recent call last):
  File "DragNUWA_demo.py", line 221, in <module>
    DragNUWA_net = Drag("cuda:0", 'models/drag_nuwa_svd.pth', 'DragNUWA_net.py', 320, 576, 14)
  File "DragNUWA_demo.py", line 72, in __init__
    state_dict = file2data(model_path, map_location='cpu')
  File "/home/arthur/dev/ai/DragNUWA/utils.py", line 161, in file2data
    data = torch.load(filename, map_location=kwargs.get('map_location'))
  File "/home/arthur/.anaconda3/envs/DragNUWA/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/arthur/.anaconda3/envs/DragNUWA/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/arthur/.anaconda3/envs/DragNUWA/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/drag_nuwa_svd.pth'
```

What is **models/drag_nuwa_svd.pth** and where do I get it?

Thanks.

**Comment by tianrengao** [comment]
You have to rename the 4799.pth to models/drag_nuwa_svd.pth
